# PostreSQL
#   gem install pg
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'pg'
development:
  adapter: postgresql
  encoding: utf8
  database: railstutorial1
  username: sample_app
  password: password
  host: 192.168.33.10
  port: 5432
  pool: 10

test:
  adapter: postgresql
  encoding: utf8
  database: railstutorial1_test
  username: sample_app
  password: password
  host: 192.168.33.10
  port: 5432
  pool: 10
